version: '3.4'

services:
  zbw.auftragsverwaltung.api:
    image: ${DOCKER_REGISTRY-}zbwauftragsverwaltungapi
    build:
      context: .
      dockerfile: src/zbw.Auftragsverwaltung.Api/Dockerfile
    depends_on:
     - db
  zbw.auftragsverwaltung.webapp:
    image: ${DOCKER_REGISTRY-}zbwauftragsverwaltungwebapp
    build:
      context: .
      dockerfile: src/zbw.Auftragsverwaltung.WebApp/Dockerfile
    depends_on:
     - db
     - zbw.auftragsverwaltung.api
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
     - 1433:1433
