version: '3.4'

services:
  zbw.auftragsverwaltung.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development-Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  #zbw.auftragsverwaltung.BlazorApp:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development-Docker
  #  ports:
  #    - "9000:80"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  zbw.auftragsverwaltung.db:
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
     - 1433:1433