version: '3.4'

services:
  zbw.auftragsverwaltung.api:
    image: ${DOCKER_REGISTRY-}zbwauftragsverwaltungapi
    build:
      context: .
      dockerfile: src/zbw.Auftragsverwaltung.Api/Dockerfile

  zbw.auftragsverwaltung.webapp:
    image: ${DOCKER_REGISTRY-}zbwauftragsverwaltungwebapp
    build:
      context: .
      dockerfile: src/zbw.Auftragsverwaltung.WebApp/Dockerfile

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
