version: '3.4'

services:
  zbw.auftragsverwaltung.api:
    image: ${DOCKER_REGISTRY-}zbwauftragsverwaltungapi
    build:
      context: .
      dockerfile: src/zbw.Auftragsverwaltung.Api/Dockerfile
    depends_on:
     - zbw.auftragsverwaltung.db
  zbw.auftragsverwaltung.BlazorApp:
    image: ${DOCKER_REGISTRY-}zbwauftragsverwaltungwebapp
    build:
      context: .
      dockerfile: src/zbw.Auftragsverwaltung.BlazorApp/Dockerfile
    depends_on:
     - zbw.auftragsverwaltung.db
     - zbw.auftragsverwaltung.api
  zbw.auftragsverwaltung.db:
    image: "mcr.microsoft.com/mssql/server"