site_name: Auftragsverwaltung
theme:
    name: material
    features:
    - navigation.instant
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    icon:
      logo: /fontawesome/solid/industry
    palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
plugins:
    - drawio-exporter
    - search:
        prebuild_index: true
    - git-revision-date
repo_url: https://github.com/elbeachboy/zbw.Auftragsverwaltung
repo_name: zbw/Auftragsverwaltung
edit_uri: edit/main/docs/
markdown_extensions:
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg