name: Generate Doc

on:
  workflow_dispatch:
jobs:
  deploy:
    env:
        drawio-version: 14.5.1
        drawio-arch: amd64
        drawio-sha256sum: 0cabdf1e9a051fc38672a9233b1b2d5368d2a776fe3d3f5e09a823278b899976
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Install Draw.io Desktop (Linux)
        if: runner.os == 'Linux'
        run: |
          set -euo pipefail
          drawio_deb="drawio-${{ env.drawio-arch }}-${{ env.drawio-version }}.deb"
          drawio_url="https://github.com/jgraph/drawio-desktop/releases/download/v${{ env.drawio-version }}/drawio-${{ env.drawio-arch }}-${{ env.drawio-version }}.deb"
          curl -L -o "$drawio_deb" "$drawio_url"
          sha256sum --check <<<"${{ env.drawio-sha256sum }}  $drawio_deb"
          sudo apt-get install -y libasound2 xvfb ./"$drawio_deb"
          
      - name: Setup Phyton
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-drawio-exporter
      - run: pip install mkdocs-git-revision-date-plugin
      - run: sudo apt install libasound2 xvfb
      - run: xvfb-run -a mkdocs gh-deploy --force
