name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore zbw.Auftragsverwaltung.sln
    - name: Build
      run: dotnet build zbw.Auftragsverwaltung.sln --no-restore
    - name: Test
      run: dotnet test zbw.Auftragsverwaltung.sln --no-build --verbosity normal
  
  semantic_release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: brpaz/action-semantic-release@v1
        with:
          dry_run: "false"
          install_plugins: "semantic-release-docker semantic-release-gcr"
          branch: master
    
